# This file was generated by GoReleaser. DO NOT EDIT.
cask "bragger" do
  name "bragger"
  desc "Job application tracker and AI-powered resume generator"
  homepage "https://github.com/ewurch/bragger"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bragger"

  on_macos do
    on_intel do
      url "https://github.com/ewurch/bragger/releases/download/v#{version}/bragger_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/ewurch/bragger"
      sha256 "705fabb1581c6a3fd8cd1fb013edd6dec0921ea2c4f721ba3c4af3b0db484be6"
    end
    on_arm do
      url "https://github.com/ewurch/bragger/releases/download/v#{version}/bragger_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/ewurch/bragger"
      sha256 "da7891b9dfaa84994596a6e7f8b2f3f59b289e8cc811bdd5f79aa6345a93d53d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ewurch/bragger/releases/download/v#{version}/bragger_#{version}_linux_amd64.tar.gz",
        verified: "github.com/ewurch/bragger"
      sha256 "5ac43580b2fa7309d269969167f4b7e799840d1f5fa85f7698861c2eb1bd46f1"
    end
    on_arm do
      url "https://github.com/ewurch/bragger/releases/download/v#{version}/bragger_#{version}_linux_arm64.tar.gz",
        verified: "github.com/ewurch/bragger"
      sha256 "ccab636926db1a558393928d6d5e99867c52d3cc728f81d211c94e3b1cccef9c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bragger"]
    end
  end

  # No zap stanza required
end
