# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bragger < Formula
  desc "Job application tracker and AI-powered resume generator"
  homepage "https://github.com/ewurch/bragger"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ewurch/bragger/releases/download/v0.2.0/bragger_0.2.0_darwin_amd64.tar.gz"
      sha256 "096943af3ffd611356b2d1a647607617e8a40d8d00aa47da56fc1a550a42cc97"

      def install
        bin.install "bragger"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ewurch/bragger/releases/download/v0.2.0/bragger_0.2.0_darwin_arm64.tar.gz"
      sha256 "4b2d919092a0679b1532bc9b446fd4f90600b911da03ea0656f52de2f99c8346"

      def install
        bin.install "bragger"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ewurch/bragger/releases/download/v0.2.0/bragger_0.2.0_linux_amd64.tar.gz"
      sha256 "f42353d65b889df6e7c0d27a3f1cf8bc280ed506eb490609a7a2eb2fe695501f"
      def install
        bin.install "bragger"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ewurch/bragger/releases/download/v0.2.0/bragger_0.2.0_linux_arm64.tar.gz"
      sha256 "9dd146e218e9a29949ea4c94ccb115a89c033571d6fd6ecf01534e4ab19c7716"
      def install
        bin.install "bragger"
      end
    end
  end

  test do
    system "#{bin}/bragger", "version"
  end
end
