# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bragger < Formula
  desc "Job application tracker and AI-powered resume generator"
  homepage "https://github.com/ewurch/bragger"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ewurch/bragger/releases/download/v0.3.1/bragger_0.3.1_darwin_amd64.tar.gz"
      sha256 "a1b5639cb5f38d72fe26230e60685ea299f3e15984d381d5fd62fa0c30de01f1"

      def install
        bin.install "bragger"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ewurch/bragger/releases/download/v0.3.1/bragger_0.3.1_darwin_arm64.tar.gz"
      sha256 "de5c1355f36ca824ddacedf5d3495376d0318c8c86ced5a131870d7dbec10e5d"

      def install
        bin.install "bragger"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ewurch/bragger/releases/download/v0.3.1/bragger_0.3.1_linux_amd64.tar.gz"
      sha256 "cee6332efecc7672e89bd40fe990a528e3246f9fdee09a836e785b577835b305"
      def install
        bin.install "bragger"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ewurch/bragger/releases/download/v0.3.1/bragger_0.3.1_linux_arm64.tar.gz"
      sha256 "991ee907f155a5031b4ae72e7bcbca41ca94b8fe2ead4ef69ff8428310c4e2b0"
      def install
        bin.install "bragger"
      end
    end
  end

  test do
    system "#{bin}/bragger", "version"
  end
end
